### ISSUE TITLE
apihelper.js -> GetFileItems ska utökas till att nyttja alla features av API-metoden med samma namn.

### ISSUE THREAD

**Issue by flinux84** [flinux84/CloudMine#65]
apihelper.js -> Funktionen för GetFileItems ska kunna ta inparameter för att stödja sök, sortering, pagination. Funktion ska också returnera X-PageInfo

**Comment by KimKarlsson** [comment]
finns sök och sortering implementerat..

**Comment by KimKarlsson** [comment]
pagination fnns.. Vet inte vad X-PageInfo är dock

**Comment by flinux84** [comment]
mm vi kan nog stänga denna nu, ska se om jag kan få paginering att rita upp dynamiskt.
